### ISSUE TITLE
Make upstart respawn limit configurable

### ISSUE THREAD

**Issue by jage** [twingly/capistrano-twingly#16]
We should make it possible to set a respawn limit, some of our services get stuck in infinite loops on some errors.

We probably need to define a new [foreman export template](https://github.com/ddollar/foreman/blob/master/data/export/upstart/process.conf.erb) to set the [respawn limit](http://upstart.ubuntu.com/wiki/Stanzas#respawn_limit)

**Comment by walro** [comment]
We're going to drop upstart support, see #51. However, systemd do have a similar concept implemented by `StartLimitIntervalSec` and friends. See https://www.freedesktop.org/software/systemd/man/systemd.unit.html

That being said I will proceed and close this until we feel a need for it.
