### ISSUE TITLE
Release gem to rubygems.org

### ISSUE THREAD

**Issue by jage** [twingly/capistrano-twingly#24]
Let Travis-CI release the gem when tagging: http://docs.travis-ci.com/user/deployment/rubygems/

Update all depending Twingly projects Gemfile's when it's done.

**Comment by dentarg** [comment]
https://github.com/svenfuchs/gem-release might be useful

**Comment by dentarg** [comment]
Perhaps it's enough to do like we do in other projects (e.g. https://github.com/twingly/twingly-url), here are those instructions:

```markdown
## Release workflow

* Bump the version in `lib/twingly/version.rb` in a commit, no need to push (the release task does that).

* Make sure you are logged in as [twingly][twingly-rubygems] at RubyGems.org.

* Build and [publish](http://guides.rubygems.org/publishing/) the gem. This will create the proper tag in git, push the commit and tag and upload to RubyGems.

        bundle exec rake release

[twingly-rubygems]: https://rubygems.org/profiles/twingly
[ruby-prof]: http://ruby-prof.rubyforge.org/
```

**Comment by dentarg** [comment]
I'm going to [backdate](http://stackoverflow.com/a/21759466/525616) tags for old versions.

From `$ git log --oneline capistrano-twingly.gemspec | cut -d " " -f 1 | while read id ; do ; echo $id ; git log -1 --oneline -p $id | grep '+  spec.version' ; done` i manually composed this list of old versions:

98dca9b v2.0.1
921f23d v2.0.0
38ddc11 v1.8.0
66461c1 v1.7.1
275a993 v1.7.0
8147d08 v1.6.2
1fbfa72 v1.6.1
1feb437 v1.6.0
782c50a v1.5.1
3bf3e7e v1.5.0
76400b4 v1.4.0
5effecf v1.3.0
674f742 v1.2.1
f2bd538 v1.1.1
dd632d8 v1.0.1
1b849e6 v1.0.0
756883a v0.1.4
c06791f v0.1.3
b4c2645 v0.1.2
87ae967 v0.1.1
0c5897c v0.1.0

**Comment by dentarg** [comment]
Done: https://github.com/twingly/capistrano-twingly/releases

I had the list above as `~/Downloads/capistrano-twingly-versions` and used some Ruby + shell:

```ruby
#!/usr/bin/env ruby

File.readlines(File.expand_path("~/Downloads/capistrano-twingly-versions")).map(&:chomp).map(&:split).each do |commit,tag|
  puts "git checkout #{commit}"
  puts "GIT_COMMITTER_DATE=\"$(git show --format=%aD | head -1)\" git tag -a #{tag} -m \"#{tag}\""
end
```

```shell
~/twingly/ruby/capistrano-twingly master
$ ~/Downloads/capistrano-twingly-versions.rb | sh
...
```
