### ISSUE TITLE
foreman isn't defined as an dependency

### ISSUE THREAD

**Issue by dentarg** [twingly/capistrano-twingly#29]
The Upstart tasks uses `foreman export`: https://github.com/twingly/capistrano-twingly/blob/5dcbdb2ae1aab0035d77649746f000eb2c04bccd/lib/capistrano/twingly/tasks/upstart.rake#L8

I think it's pure luck that all of our projects already have `foreman` in their `Gemfile`s :)

**Comment by dentarg** [comment]
> I think it's pure luck that all of our projects already have foreman in their Gemfiles :)

Though I don't think there is any project that has a reason to have it, besides capistrano-twingly.

**Comment by jage** [comment]
I guess we missed it when we extracted the capistrano tasks to a gem.
