### ISSUE TITLE
Certain changes in deploy configuration leave old Upstart configuration on app servers

### ISSUE THREAD

**Issue by dentarg** [twingly/capistrano-twingly#31]
When we change number of workers, old upstart config files is left on the server, and you have to remember to perform [manual cleanup](https://github.com/twingly/zambezi/commit/04d54fb2c9d01f959482753ced773fc23c184c7a#commitcomment-18703346) like this:

```
ansible appservers -b -m shell -a 'find /etc/init -name "*zambezi*" -exec rm {} \;'
```

before starting the application with the new settings.

Original report: https://trello.com/c/IViPCl8t

**Comment by walro** [comment]
I think we should use foreman's [formation](https://ddollar.github.io/foreman/#RUNNING) to control the number of processes rather than doing it manually via loop constructs. It seems like it can clean itself up: https://github.com/ddollar/foreman/pull/647

**Comment by walro** [comment]
> Probably not a good idea though. If something goes wrong and`fetch(:application)` returns an empty string for some reason, everything in `/etc/init` will be removed.

Just a sanity check could take care of that I suppose.

**Comment by roback** [comment]
It looks like this will be solved when switching to systemd. I renamed the process in twingly/test from `web` to `someprocess` and when deploying it the the old web processes gets removed.

```
...
00:03 deploy:export_systemd
      01 sudo /usr/local/bin/chruby-exec 2.4 -- /home/deploy/twingly-test/shared/bin/foreman export systemd /etc/systemd/system -a twingly-test -u `whoami` -l /home/deploy/twingly-…
      01 [foreman export] cleaning up: /etc/systemd/system/twingly-test.target
      01 [foreman export] cleaning up: /etc/systemd/system/twingly-test-web.target
      01 [foreman export] cleaning up: /etc/systemd/system/twingly-test-web@.service
      01 [foreman export] cleaning up directory: /etc/systemd/system/twingly-test-web.target.wants
      01 [foreman export] writing: twingly-test-someprocess@.service
      01 [foreman export] creating: twingly-test-someprocess.target.wants
      01 [foreman export] symlinking: twingly-test-someprocess.target.wants/twingly-test-someprocess@5000.service -> ../twingly-test-someprocess@.service
      01 [foreman export] writing: twingly-test-someprocess.target
      01 [foreman export] writing: twingly-test.target
    ✔ 01 deploy@localhost 0.175s
      02 sudo /bin/systemctl daemon-reload
    ✔ 02 deploy@localhost 0.116s
      03 sudo systemctl restart twingly-test.target || sudo systemctl start twingly-test.target
    ✔ 03 deploy@localhost 0.012s
...
```

**Comment by roback** [comment]
> It looks like this will be solved when switching to systemd. I renamed the process in twingly/test from `web` to `someprocess` and when deploying it the the old web processes gets removed.

The files gets removed, but the service is still active, even after a daemon-reload:

```
$ sudo systemctl daemon-reload
$ systemctl status twingly-test-web.target
● twingly-test-web.target
   Loaded: not-found (Reason: No such file or directory)
   Active: active since Thu 2019-04-25 07:09:59 UTC; 35min ago
```

I think we may need to stop/disable the service when deploying.

**Comment by roback** [comment]
> I think we may need to stop/disable the service when deploying.

Running `systemctl stop ...` seems to be enough, no need to disable the service.

**Comment by roback** [comment]
I have deployed our test project to vagrant a few times with different number of processes, and when deploying to Ubuntu 18.04 (Systemd), all Systemd units belonging to the test project, even those that has been removed from the procfile gets cleaned up successfully.

When deploying to Ubuntu 14.04 (Upstart) however, the behaviour is the same as before, ie. old processes are left behind.

I will remove the critical label, but keep this issue open since this gem still supports Upstart, even though we don't use it ourselves anymore.

**Comment by walro** [comment]
I think we should drop upstart support so that we can close this.

**Comment by dentarg** [comment]
Agree

**Comment by walro** [comment]
> I think we should drop upstart support so that we can close this.

See #51
