### ISSUE TITLE
Lock down capistrano dependency 

### ISSUE THREAD

**Issue by dentarg** [twingly/capistrano-twingly#32]
In https://github.com/twingly/capistrano-twingly/commit/275a99362718fd6a601ce03afb48b6f0f2e82d1d we opened up from any capistrano 3.2.x version to any 3.x version, but I don't think that's such a good idea.

As seen in their [changelog](https://github.com/capistrano/capistrano/blob/master/CHANGELOG.md), capistrano isn't working with [Semantic Versioning](http://semver.org/):

>MAJOR version when you make incompatible API changes,
>MINOR version when you add functionality in a backwards-compatible manner, and
>PATCH version when you make backwards-compatible bug fixes.

They are deprecating and removing stuff in the "minor" versions (e.g. 3.7: https://github.com/capistrano/capistrano/blob/master/UPGRADING-3.7.md).

As we don't have any good tests here, we should lock it down to a known good version.

**Comment by walro** [comment]
Ah, can we keep the patch version floating or do you advocate for specific version lock?

**Comment by dentarg** [comment]
I think patch versions are okay, seems to be about bugfixes.

**Comment by walro** [comment]
Yeah, my impression too from browsing the changelog.
