### ISSUE TITLE
Set LANG=en_US.UTF-8 by default

### ISSUE THREAD

**Issue by dentarg** [twingly/capistrano-twingly#34]
All apps created on Heroku have `LANG=en_US.UTF-8` by default, so I think it makes sense to make it the default for capistrano-twingly and by that, all our apps.

We tried it out in https://github.com/twingly/wally/pull/57, to workaround problems due to not defaulting to UTF-8 (https://github.com/twingly/wally/issues/56)

**Comment by dentarg** [comment]
Hmm, this wasn't as straightforward as I thought it should be

`deploy.rb` example

```ruby
set :procfile_contents, lambda {
  contents = ""
  contents << "wally: chruby-exec #{fetch(:chruby_ruby)} -- "
  contents << "RUBY_ENV=production "
  contents << "LANG=en_US.UTF-8 "
  contents << "envconsul --prefix applications/#{APP_NAME} "
  contents << "bundle exec ruby wally.rb "
  contents
}
```

`upstart.rake`

```ruby
    desc 'Generate Procfile'
    task  :generate_procfile do
      Dir.mkdir('tmp') unless Dir.exist?('tmp')

      File.open('tmp/Procfile', 'w') do |conf|
        fetch(:procfile_contents).each_line do |line|
          conf.puts "#{line.chomp} 2>&1 | logger -t #{fetch(:app_name)}"
        end
      end
    end
```

But I shall see if I can come up with something.

**Comment by dentarg** [comment]
I think one way could be to generate an `.env` on the fly, from http://ddollar.github.io/foreman/:

>ENVIRONMENT
>If a .env file exists in the current directory, the default environment will be read from it. This file should contain key/value pairs, separated by =, with one key/value pair per line.

**Comment by walro** [comment]
easy, just split `line` on the assumption that ` -- ` exists and inject desired stuff! :trollface:

**Comment by walro** [comment]
> I think one way could be to generate an .env on the fly, from http://ddollar.github.io/foreman/:

That sounds reasonable!

**Comment by jage** [comment]
How about we set the environment variables (`RUBY_ENV` and `LANG`) in Consul?

We create a common directory with the common keys in, then something like this:

```
envconsul -prefix applications/common -prefix applications/wally
```

Then we switch to envconsul for all apps (no need to remove the ZooKeeper-implementation now).

**Comment by walro** [comment]
> How about we set the environment variables (RUBY_ENV and LANG) in Consul?

It's discussed a bit here and down: https://github.com/twingly/wally/pull/57#issuecomment-247616531

**Comment by dentarg** [comment]
This is what I did... perhaps too hacky? :)

```diff
$ git d
diff --git a/lib/capistrano/twingly/tasks/upstart.rake b/lib/capistrano/twingly/tasks/upstart.rake
index 07d02a7..8844984 100644
--- a/lib/capistrano/twingly/tasks/upstart.rake
+++ b/lib/capistrano/twingly/tasks/upstart.rake
@@ -23,17 +23,22 @@ namespace :deploy do
   end

   namespace :foreman do
-    desc 'Upload Procfile to server'
+    desc 'Upload .env and Procfile to server'
     task :upload_procfile do
       on roles(:app) do
+        upload! 'tmp/.env', "#{fetch(:deploy_to)}/current/.env"
         upload! 'tmp/Procfile', "#{fetch(:deploy_to)}/current/Procfile"
       end
     end

-    desc 'Generate Procfile'
+    desc 'Generate .env and Procfile'
     task  :generate_procfile do
       Dir.mkdir('tmp') unless Dir.exist?('tmp')

+      File.open('tmp/.env', 'w') do |dotenv|
+        dotenv.puts "LANG=en_US.UTF-8"
+      end
+
       File.open('tmp/Procfile', 'w') do |conf|
         fetch(:procfile_contents).each_line do |line|
           conf.puts "#{line.chomp} 2>&1 | logger -t #{fetch(:app_name)}"
```

**Comment by walro** [comment]
Not really that much hacky than the whole procfile generation. The task name does not really fit anymore though, perhaps worth walking the extra mile and define a separate task for the env stuff

**Comment by dentarg** [comment]
@jage Hmm, I like the idea, it's more flexible than hardcoding something here. One downside(?) with the common prefix would be that, when we change some value/add a key, all apps will be restarted at the same time... :)

**Comment by dentarg** [comment]
(I created `applications/common` and tried it with the test application)

**Comment by jage** [comment]
> One downside(?) with the common prefix would be that, when we change some value/add a key, all apps will be restarted at the same time... :)

Indeed, especially serious for web applications. This might improve it:

> splay - The maximum time to wait before restarting the program, from which a random value is chosen.

https://github.com/hashicorp/envconsul

I would say it should be something like 30s or 60s (bruce is slow).

**Comment by dentarg** [comment]
Yes, `splay` should improve that, thanks for reminding me about it, I knew I've read about it earlier. Would be nice if we could have an [`-config` file](https://github.com/hashicorp/envconsul#configuration-file) for `envconsul`, so we don't have to specify common `envconsul` options in every project... :)

**Comment by dentarg** [comment]
Let's go with envconsul, and not hardcode `LANG` here. I've created https://github.com/twingly/ansible/issues/548 where we can continue talking about envconsul.
