### ISSUE TITLE
Default to start apps with envconsul

### ISSUE THREAD

**Issue by dentarg** [twingly/capistrano-twingly#37]
One (non-test) application have started using `envconsul`, with [our common configuration](https://github.com/twingly/wally/pull/66), like this:

``` ruby
set :procfile_contents, lambda {
  contents = ""
  contents << "wally: chruby-exec #{fetch(:chruby_ruby)} -- "
  contents << "envconsul "
  contents << "-config /home/deploy/ruby-env.hcl "
  contents << "-prefix applications/#{APP_NAME} "
  contents << "bundle exec ruby wally.rb "
  contents
}
```

We want this to be the default for all applications using capistrano-twingly.

Some changes to the generated upstart files are needed though, from https://github.com/twingly/wally/issues/24:

> > We could try defining that wally is dependant on consul being alive and kicking
> 
> I think this would be the following in the upstart-file:
> 
> ```
> start on started consul
> ```
> 
> Currently we have, "start as soon as the multi-user system is booted":
> 
> ```
> start on runlevel [2345]
> ```
> 
> http://upstart.ubuntu.com/cookbook/#order-in-which-jobs-which-start-on-the-same-event-are-run

> > In the upstart file generated by foreman export?
> 
> Yes, foreman exports several upstart files, but this should be changed in the "first/top" file:
> 
> ```
> /etc/init/twingly-wally.conf # This file should have a different start-statement
> /etc/init/twingly-wally.override
> /etc/init/twingly-wally-wally-1.conf
> /etc/init/twingly-wally-wally.conf
> ```

**Comment by jage** [comment]
> We could try defining that wally is dependant on consul being alive and kicking

I don't think this is necessary, at least not in the first version.

Did a quick test with consul stopped, then started after a few seconds. envconsul will just wait and poll before executing the command, ensuring the variables are set.

```
$ /opt/consul/bin/envconsul -prefix applications/common env
2016/12/30 15:31:51 [ERR] (view) "storeKeyPrefix(applications/common)" store key prefix: error fetching: Get http://127.0.0.1:8500/v1/kv/applications/common?recurse=&stale=&wait=60000ms: dial tcp 127.0.0.1:8500: getsockopt: connection refused
2016/12/30 15:31:51 [ERR] (runner) watcher reported error: store key prefix: error fetching: Get http://127.0.0.1:8500/v1/kv/applications/common?recurse=&stale=&wait=60000ms: dial tcp 127.0.0.1:8500: getsockopt: connection refused

2016/12/30 15:31:56 [ERR] (view) "storeKeyPrefix(applications/common)" store key prefix: error fetching: Get http://127.0.0.1:8500/v1/kv/applications/common?recurse=&stale=&wait=60000ms: dial tcp 127.0.0.1:8500: getsockopt: connection refused
2016/12/30 15:31:56 [ERR] (runner) watcher reported error: store key prefix: error fetching: Get http://127.0.0.1:8500/v1/kv/applications/common?recurse=&stale=&wait=60000ms: dial tcp 
127.0.0.1:8500: getsockopt: connection refused

LANG=en_US.UTF-8
$                                                                                                                                                                       
```

**Comment by jage** [comment]
> set :procfile_contents, lambda {
>   contents = ""
>   contents << "wally: chruby-exec #{fetch(:chruby_ruby)} -- "
>   contents << "envconsul "
>   contents << "-config /home/deploy/ruby-env.hcl "
>   contents << "-prefix applications/#{APP_NAME} "
>   contents << "bundle exec ruby wally.rb "
>   contents
> }

I think we might want to change how we pass on the Procfile contents (to avoid parsing it).

The challenge is that the input string `web: chruby-exec 2.2 -- bundle exec ruby app.rb` should be converted to `web: chruby-exec 2.2 -- envconsul bundle exec ruby app.rb` safely.

**Comment by dentarg** [comment]
Maybe it's better not to provide a default value. One benefit from that is that it will always be obvious how the app is started, by looking at the config for that app, even if you don't know what the default is.

**Comment by walro** [comment]
I think we can close this, seeing that we very rarely create new Capistrano-dependant applications these days. The ones we do have setup already do this ceremonial dance.

WDTY @twingly/dev ?

**Comment by dentarg** [comment]
Sure
