### ISSUE TITLE
Add systemd support

### ISSUE THREAD

**Issue by dentarg** [twingly/capistrano-twingly#45]
For Ubuntu 18.04

https://ddollar.github.io/foreman/#SYSTEMD-EXPORT

I guess it will be similar to https://github.com/twingly/capistrano-twingly/blob/v3.0.0/lib/capistrano/twingly/tasks/upstart.rake

**Comment by dentarg** [comment]
Not sure how to deal with

https://github.com/twingly/capistrano-twingly/blob/24a975e9a7cb124dbdb7961687782801f40b2fe8/lib/capistrano/twingly.rb#L16

**Comment by dentarg** [comment]
> Not sure how to deal with

We can just release a new version of this gem, without that line, and when we update in our projects, we have to add it, or the add one for systemd

The tricky thing is of course if an application wants to run on both 14.04 (upstart) and 18.04 (systemd)

**Comment by jage** [comment]
Would be good to take a look at https://github.com/twingly/capistrano-twingly/issues/31 (might be solved implicitly)

**Comment by dentarg** [comment]
https://github.com/puma/puma/issues/1499 might be relevant for us

https://github.com/twingly/capistrano-twingly/blob/24a975e9a7cb124dbdb7961687782801f40b2fe8/lib/capistrano/twingly/tasks/nginx.rake#L16

**Comment by roback** [comment]
Tested the systemd export in forman and ran into the following: https://github.com/ddollar/foreman/issues/704

These are the files that gets generated (deployed our test project against vagrant):

```
$ ls -1 /etc/systemd/system/twingly-test*
/etc/systemd/system/twingly-test-web.target
/etc/systemd/system/twingly-test-web@.service
/etc/systemd/system/twingly-test.target

/etc/systemd/system/twingly-test-web.target.wants:
twingly-test-web@5000.service
```

I can manage the service when appending `.target` to the name, for example `systemctl status twingly-test.target`, but that doesn't work when using `service`:

```
$ service twingly-test.target status
Unit twingly-test.target.service could not be found.
$ service twingly-test status
Unit twingly-test.service could not be found.
$ service twingly-test@ status
Failed to get properties: Unit name twingly-test@.service is neither a valid invocation ID nor unit name.
```

**Comment by roback** [comment]
> We can just release a new version of this gem, without that line, and when we update in our projects, we have to add it, or the add one for systemd
>
> The tricky thing is of course if an application wants to run on both 14.04 (upstart) and 18.04 (systemd)

An idea would be to have two different branches in each project, one with the old version of capistrano-twingly that deploys using upstart, and another branch with the latest capistrano-twingly that uses systemd.

How to find out which servers we should deploy to in each branch I don't know. I suppose we could hardcode them instead of using `servers_from_srv_record` like we do now. Though, having to update the servers array in each project before being able to deploy isn't that nice.

**Comment by walro** [comment]
On 14.04: `sudo apt-get install systemd` :trollface:

**Comment by roback** [comment]
> An idea would be to have two different branches in each project, one with the old version of capistrano-twingly that deploys using upstart, and another branch with the latest capistrano-twingly that uses systemd. We can configure the branch that gets deployed with `set :branch, "<name>"`.

Even better: we assign each server a role: `upstart` or `systemd` and use something like the following to run different commands depending on what role the server has:

```
  task :start do
    invoke "deploy:export_service"

    on roles(:upstart) do
      sudo :start, fetch(:application)
    end

    on roles(:systemd) do
      sudo :systemctl, "start #{fetch(:application)}.target"
    end
  end
```

We would still need to know which server should have which role, but at least we don't have to use two different branches.

**Comment by dentarg** [comment]
@roback Here's an idea I think we can easily do

If we add a bit logic to our `sth.twingly.network` zone template in the Ansible repo, we could automatically deploy two SRV records: one for app servers running Ubuntu 14.04 and one for Ubuntu 18.04

And we adjust this project to work with two records instead of one + your idea about roles above

Then it should just be a matter of updating capistrano-twingly in every project, not having to change anything else when deploying

WDYT?

**Comment by roback** [comment]
> If we add a bit logic to our `sth.twingly.network` zone template in the Ansible repo, we could automatically deploy two SRV records: one for app servers running Ubuntu 14.04 and one for Ubuntu 18.04

:+1: Sounds great @dentarg. I'll make a PR with the needed changes.
